mongodb: Depends on libpcap pkg-config for Linuxbrew
`system "./build.sh", *args ` didn't work (silently...) because
`${BASH_SOURCE[0]}` was not defined so use `bash ./build.sh` instead of sh.

Fails with GCC 4.8. Fix the error:
Checking if C compiler is GCC 5.3.0 or newer...no
Checking if C++ compiler is GCC 5.3.0 or newer...no
ERROR: Refusing to build with compiler that does not meet requirements