libzdb: fix test
```
==> /usr/bin/gcc select.c -L/home/linuxbrew/.linuxbrew/Cellar/libzdb/3.2.1/lib -lzdb -I/home/linuxbrew/.linuxbrew/Cellar/libzdb/3.2.1/include/zdb -o select
/usr/bin/ld: /tmp/ccSmwSZO.o: undefined reference to symbol 'pthread_setspecific@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```