snapcraft: Fix build for Linux
- The `cffi` package was failing to install for snapcraft because we
  were missing a dependency and its location:
  ```
  ==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/snapcraft--cffi-20190705-15295-1gqcfqj/cffi-1.11.4
  Last 15 lines from /root/.cache/Homebrew/Logs/snapcraft/04.pip:
  Removed build tracker '/tmp/pip-req-tracker-6j1hbkub'
  ERROR: Command "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-yui2p5h7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v8780eqo/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-req-build-yui2p5h7/
  ```