mongodb: Depends on libpcap for Linuxbrew
Building mongoreplay...
vendor/src/github.com/google/gopacket/pcap/pcap.go:19:18:
fatal error: pcap.h: No such file or directory